### ISSUE TITLE
Checking which View is active

### ISSUE THREAD

**Issue by jemshit** [FireZenk/Naviganto#11]
Hi, in samples, there is `DetailActivity` which hosts both `ProfileView` and `ProductView`, so how to check which one is active and visible ?

**Comment by FireZenk** [comment]
Both are loaded as a child of the `placeholder`, first `ProfileView` using `ProfileRoute` and when user clicked `nextButton`, loads the route: `ProductViewRoute` to put `ProductView` as a child of `placeholder`; in all cases is it required that the `placeholder` extends any `ViewGroup`

**Comment by jemshit** [comment]
So back to the question, how do we check which one is visible? like checking if placeholder contains child ProductView etc .. ?

**Comment by FireZenk** [comment]
You can use the sdk for this, something like: `viewGroup.getChildAt(..) instanceOf SomeView`
