### ISSUE TITLE
v2.0 gradle sync failed

### ISSUE THREAD

**Issue by nelo686** [FireZenk/Naviganto#9]
Hi Jorge,

I'm trying to update ConceptRouter dependency version from 1.1.0 to 2.0, but I can't sync gradle properly. I do it like readme says:

```[java]
repositories {
            ...
            maven { url 'https://github.com/FireZenk/maven-repo/raw/master/'}
    }
    dependencies {
            ...
            compile 'org.firezenk:conceptrouter:2.0@aar'
            provided 'javax.annotation:jsr250-api:1.0'
    }
```

can you help me?
Thanks

**Comment by FireZenk** [comment]
Hi Daniel, maybe is the lib version, is 2.0.0 not 2.0

**Comment by nelo686** [comment]
I thought about that. I tried but it's the same.

`compile 'org.firezenk:conceptrouter:2.0.0@aar'`

Error:Could not find org.firezenk:conceptrouter:2.0.0.

**Comment by FireZenk** [comment]
Try again with 2.0.0, there was a mistake into the maven's folder naming

**Comment by nelo686** [comment]
It works like a charm. Thanks!!

**Comment by FireZenk** [comment]
That's great :) Would be nice if you can give some feedback when you use
ConceptRouter!
